// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6Z3GgabEj9jR09u1V9RBLrrf3XK7_uI',
    appId: '1:1010216733110:web:c9e36cc0b1f2b801561917',
    messagingSenderId: '1010216733110',
    projectId: 'instagram-clone-877ce',
    authDomain: 'instagram-clone-877ce.firebaseapp.com',
    storageBucket: 'instagram-clone-877ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdO8UzEL_2QddE7Cd5r62fQ7Inm5_JhM',
    appId: '1:1010216733110:android:0685a61d34034108561917',
    messagingSenderId: '1010216733110',
    projectId: 'instagram-clone-877ce',
    storageBucket: 'instagram-clone-877ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehMKF6VFLv5HUsNXQIRp0Q0lFVQLprh4',
    appId: '1:1010216733110:ios:2165146d77fd2280561917',
    messagingSenderId: '1010216733110',
    projectId: 'instagram-clone-877ce',
    storageBucket: 'instagram-clone-877ce.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehMKF6VFLv5HUsNXQIRp0Q0lFVQLprh4',
    appId: '1:1010216733110:ios:2165146d77fd2280561917',
    messagingSenderId: '1010216733110',
    projectId: 'instagram-clone-877ce',
    storageBucket: 'instagram-clone-877ce.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6Z3GgabEj9jR09u1V9RBLrrf3XK7_uI',
    appId: '1:1010216733110:web:6917fad224a9bfc7561917',
    messagingSenderId: '1010216733110',
    projectId: 'instagram-clone-877ce',
    authDomain: 'instagram-clone-877ce.firebaseapp.com',
    storageBucket: 'instagram-clone-877ce.firebasestorage.app',
  );
}
